Data Gathering

In [61]:
import pandas as pd
data = pd.read_csv('huge_1M_titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

DATA PREPROCESSING

In [62]:
data.shape #Count of records
data.info() #Data types and null values
data.isnull().sum() #Count of null values in each column
data.drop(columns=['PassengerId','Name','Age','Ticket','Cabin'], inplace=True) #Dropping irrelevant columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  object
 4   Sex          1000000 non-null  object
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  object
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   object
 11  Embarked     997760 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 91.6+ MB

In [63]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [64]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [65]:
data['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [66]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

DATA CLEANING

In [67]:
data['Embarked'] = data['Embarked'].replace({'S': 'Southampton', 'C': 'Cherbourg', 'Q': 'Queenstown'})
data.dropna(subset=['Embarked'], inplace=True) #Dropping rows with null values in 'Embarked' column
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165    Cherbourg
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416    Cherbourg
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769    Cherbourg

In [68]:
data.isnull().sum() 
data['Fare'] = data['Fare'].astype('int8') #Converting 'Fare' column to integer type
data.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76    Cherbourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12    Cherbourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4    Cherbourg

DATA ENCODING

In [69]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
0         1       1    0      0      0    76    Cherbourg
1         0       3    1      0      0    10  Southampton
2         0       3    1      0      0    12    Cherbourg
3         0       3    1      0      0    13  Southampton
4         0       3    1      0      0     4    Cherbourg

In [70]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder(sparse_output=False)      
Embarked=onehot.fit_transform(data[['Embarked']])

In [71]:
Embarked=pd.DataFrame(Embarked, columns=onehot.get_feature_names_out())
Embarked

        Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                      1.0                  0.0                   0.0
1                      0.0                  0.0                   1.0
2                      1.0                  0.0                   0.0
3                      0.0                  0.0                   1.0
4                      1.0                  0.0                   0.0
...                    ...                  ...                   ...
997755                 0.0                  0.0                   1.0
997756                 0.0                  0.0                   1.0
997757                 0.0                  0.0                   1.0
997758                 0.0                  0.0                   1.0
997759                 0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [72]:
data=pd.concat([data.drop(columns=['Embarked']), Embarked], axis=1)
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

DATA SCALING

In [73]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Cherbourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='object')

In [74]:
num_cols = ['Pclass','SibSp', 'Parch', 'Fare' ]
data[num_cols] = scale.fit_transform(data[num_cols])
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [75]:
import pickle
with  open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)
with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot, file)
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scale, file)

TRAIN,VALIDATION,TEST,SPLIT

In [ ]:
X=data.drop(columns=['Survived'])
y=data['Survived']

In [77]:
X.head()

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [78]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Survived, dtype: float64

In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)
x_train, x_val, y_train, y_val=train_test_split(x_train, y_train, test_size=0.25, random_state=42)

MODEL BUILDING STEPS

In [89]:
import tensorflow

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [92]:
model = Sequential([Dense(64,input_shape=(x_train.shape[1],), activation='relu'),Dense(32, activation='relu'),Dense(1, activation='sigmoid')])

n:\04_Technologies\05_AI\GenAI\Python\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [93]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

Model Compilation --> Optimizer , Loss , Metrics

In [95]:
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)   
tensorflow.keras.losses.BinaryCrossentropy()

In [96]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [97]:
stopping_callback =EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [100]:
model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=3, callbacks=[stopping_callback])

Epoch 1/3
18750/18750 ━━━━━━━━━━━━━━━━━━━━ 31s 2ms/step - accuracy: 0.6169 - loss: nan - val_accuracy: 0.6168 - val_loss: nan
Epoch 2/3
18750/18750 ━━━━━━━━━━━━━━━━━━━━ 36s 2ms/step - accuracy: 0.6169 - loss: nan - val_accuracy: 0.6168 - val_loss: nan
Epoch 3/3
18750/18750 ━━━━━━━━━━━━━━━━━━━━ 35s 2ms/step - accuracy: 0.6169 - loss: nan - val_accuracy: 0.6168 - val_loss: nan

In [ ]:
model.save('ann_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [2]:
from tensorflow.keras.models import load_model
import pickle
import tensorflow as tf
import pandas as pd

In [103]:
with open('label_encoder.pkl', 'rb') as file:
    le = pickle.load(file)
with open('onehot_encoder.pkl', 'rb') as file:
    onehot = pickle.load(file)  
with open('scaler.pkl', 'rb') as file:  
    scaler = pickle.load(file)

In [ ]:
model = load_model('ann_model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [110]:
user = {'Pclass': 3, 'Sex': 'female','SibSp': 1,'Parch': 1,'Fare': 11, 'Embarked': 'Queenstown'}

In [111]:
user=pd.DataFrame([user])

In [112]:
user

   Pclass     Sex  SibSp  Parch  Fare    Embarked
0       3  female      1      1    11  Queenstown

In [113]:
user['Sex'] = le.transform(user['Sex'])